apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohort-middleware-deployment
  annotations:
    gen3.io/network-ingress: "cohort-middleware"
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: cohort-middleware
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cohort-middleware
        public: "yes"
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cohort-middleware
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: cohort-middleware-config
          secret:
            secretName: cohort-middleware-config
      containers:
        - name: cohort-middleware
          GEN3_COHORT-MIDDLEWARE_IMAGE|-image: quay.io/cdis/cohort-middleware:latest-|
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_health
              port: 8080
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: cohort-middleware-config
              readOnly: true
              mountPath: /config/development.yaml
              subPath: development.yaml
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 256Mi
